### ISSUE TITLE
Provide BymlSortedMap implementation or SortMapKeys in serializer options

### ISSUE THREAD

**Issue by jupahe64** [EPD-Libraries/BymlLibrary#1]
# The Problem
Some games require the entries of a BymlMap to be sorted by their keys (alphabetical/ordinal) so it can do a lookup via binary search.
The BymlMap in this library simply saves them in the order they are stored in the *_entries* array of `Dictionary<TKey, TValue>`, this order in most cases is NOT ordinal so the keys get written in the **wrong** order. 

# Proposed Solution
There are 2 easy fixes with a small performance drawback:
1. Extend SortedList instead (a dictionary with the keys in the correct oder), on big maps lookup will be slower O(1) -> O(log n)
2. Sort the keys everytime before saving, small memory and performance overhead

I personaly would go with option 1

**Comment by ArchLeaders** [comment]
I would consider it the user's responsibility to order the keys, but I'll look into a sorted map implementation for convenience.

**Comment by jupahe64** [comment]
From [learn.microsoft.com](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0&redirectedfrom=MSDN#remarks)
![image](https://github.com/EPD-Libraries/BymlLibrary/assets/33004544/74907e51-9455-411f-a109-7ee28a9181a4)

So it's not really the user's fault if keys get stored in the wrong order

**Comment by ArchLeaders** [comment]
True enough, I thought I used OrderedDictioanry, I'll update that and then implement a sorted dictionary for other purposes.

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/EPD-Libraries/BymlLibrary/commit/d8e04157c3c88928199473fa6d6263d06ecd883f

(`std::map` is sorted so I figured it made sense to always sort them)
