### ISSUE TITLE
Alignment is ignored when saving file nodes

### ISSUE THREAD

**Issue by dt-12345** [EPD-Libraries/BymlLibrary#3]
File nodes (0xA2) contain a u32 file size and a u32 alignment followed by the file data. Saving these nodes does not work properly as the alignment value is ignored when writing, see [BymlWriter.cs](https://github.com/EPD-Libraries/BymlLibrary/blob/2ba228e6e6edf126ae3778ecaad917b956dbb8ca/src/BymlLibrary/Writers/BymlWriter.cs#L150). This causes files using this node type to break when saved. The writer should be aligned to the requested alignment then moved back 8 bytes before writing.

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/EPD-Libraries/BymlLibrary/commit/dfb6fe2e4d6348d3febcd739351d80704c47237b
